import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../theme/app_theme.dart';
import '../../widgets/flower_background.dart';
import 'disclaimer_screen.dart';

class TermsScreen extends StatefulWidget {
  const TermsScreen({super.key});

  @override
  State<TermsScreen> createState() => _TermsScreenState();
}

class _TermsScreenState extends State<TermsScreen> {
  bool _accepted = false;
  final ScrollController _scrollController = ScrollController();

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FlowerBackground(
        child: SafeArea(
          child: Stack(
            children: [
              // Scrollable content
              SingleChildScrollView(
                controller: _scrollController,
                padding: const EdgeInsets.fromLTRB(24, 24, 24, 120),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Center(
                      child: Column(
                        children: [
                          const Text('🪷', style: TextStyle(fontSize: 48)),
                          const SizedBox(height: 12),
                          Text('Terms & Conditions',
                              style: GoogleFonts.playfairDisplay(
                                fontSize: 26,
                                fontWeight: FontWeight.bold,
                                color: AppColors.darkBrown,
                              )),
                          const SizedBox(height: 4),
                          Text('Last Updated: May 2026',
                              style: GoogleFonts.lato(
                                  fontSize: 12, color: AppColors.warmGrey)),
                        ],
                      ),
                    ),
                    const SizedBox(height: 28),

                    _buildSection('1. Acceptance of Terms',
                        'By accessing or using GitaSetu, you agree to be bound by these Terms. If you do not agree, do not use the application.'),
                    _buildSection('2. Educational and Spiritual Nature',
                        'GitaSetu is an AI-powered spiritual assistant intended for educational and philosophical exploration of the Bhagavad Gita. It provides interpretations based on historical texts and large language models (LLM).'),
                    _buildSection('3. Generative AI Disclaimer',
                        'Content is AI-Generated. You acknowledge that responses are generated by Artificial Intelligence. AI can hallucinate or provide inaccurate, incomplete, or biased information. GitaSetu does not guarantee the scriptural or factual accuracy of any response. The AI is not a spiritual guru, priest, or counselor.'),
                    _buildSection('4. User Responsibility & Reporting',
                        'You agree not to use the app to generate hate speech, illegal content, or harmful instructions. If you encounter offensive or harmful AI content, use the in-app reporting feature immediately.'),
                    _buildSection('5. Data Privacy & AI Processing',
                        'Journal entries are stored only on your device. A journal entry is sent for temporary AI reflection only when you request it. Mood inputs and chat prompts are processed only for the current response and are not saved by the app.'),
                    _buildSection('6. Privacy Policy',
                        'Guru and admin-managed content may be stored remotely. Personal journal, mood, and chat history are not used for cloud persistence in the app. We never sell your data to third parties.'),
                    _buildSection('7. Account Deletion',
                        'You may request complete deletion of your account and all associated data at any time from the Settings screen or by contacting us. All data will be permanently deleted within 30 days.'),
                    _buildSection('8. ISKCON Affiliation',
                        'This app is built in alignment with ISKCON\'s mission to spread the teachings of the Bhagavad Gita. We encourage users to engage with ISKCON communities and qualified devotees for deeper spiritual guidance.'),

                    const SizedBox(height: 24),

                    // Checkbox
                    GestureDetector(
                      onTap: () => setState(() => _accepted = !_accepted),
                      child: Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color:
                              _accepted ? AppColors.saffronLight : Colors.white,
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(
                            color: _accepted
                                ? AppColors.primary
                                : AppColors.border,
                          ),
                        ),
                        child: Row(
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              decoration: BoxDecoration(
                                color: _accepted
                                    ? AppColors.primary
                                    : Colors.white,
                                borderRadius: BorderRadius.circular(6),
                                border: Border.all(
                                  color: _accepted
                                      ? AppColors.primary
                                      : AppColors.border,
                                  width: 2,
                                ),
                              ),
                              child: _accepted
                                  ? const Icon(Icons.check,
                                      color: Colors.white, size: 16)
                                  : null,
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Text(
                                'I have read and agree to the Terms & Conditions',
                                style: GoogleFonts.lato(
                                  fontSize: 14,
                                  color: AppColors.darkBrown,
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 16),
                  ],
                ),
              ),

              // Fixed bottom button
              Positioned(
                bottom: 0,
                left: 0,
                right: 0,
                child: Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    color: AppColors.background,
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withValues(alpha: 0.05),
                        blurRadius: 10,
                        offset: const Offset(0, -4),
                      ),
                    ],
                  ),
                  child: SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: _accepted
                          ? () => Navigator.pushReplacement(
                                context,
                                MaterialPageRoute(
                                    builder: (_) => const DisclaimerScreen()),
                              )
                          : null,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primary,
                        foregroundColor: Colors.white,
                        disabledBackgroundColor: AppColors.border,
                        padding: const EdgeInsets.symmetric(vertical: 18),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                      ),
                      child: Text(
                        'I Agree — Continue →',
                        style: GoogleFonts.playfairDisplay(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title,
              style: GoogleFonts.playfairDisplay(
                fontSize: 15,
                fontWeight: FontWeight.bold,
                color: AppColors.darkBrown,
              )),
          const SizedBox(height: 6),
          Container(
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: AppColors.border),
            ),
            child: Text(content,
                style: GoogleFonts.lato(
                  fontSize: 13,
                  color: AppColors.warmGrey,
                  height: 1.7,
                )),
          ),
        ],
      ),
    );
  }
}
